- scripts/core/context.yml
fixes #8 
Clarifies that a context can be used by all of the devices and any sub-devices of the devices that were specified when the context was created.
> clarify that a context can also be used by sub-devices of devices

- scripts/core/EXT_Bfloat16Conversions.rst
- scripts/core/SPIRV.rst
- scripts/core/bfloat16conversions.yml
fixes #14
Adds the ZE_extension_bfloat16_conversions extension.
This extension adds no new APIs but does allow usage of bfloat16 conversion instructions in SPIR-V modules.
> add an extension for bfloat16 conversions

- scripts/core/event.yml
Fixes #9 
Relaxes the restriction prohibiting IPC events from being used with kernel timestamps.
Note: As-written these changes only apply to v1.5 implementations.  Is that correct, or is this a bugfix that should apply to earlier versions as well?
> relax restriction and allow ipc events with timestamps

- scripts/core/EXT_DeviceIpVersion.rst
- scripts/core/common.yml
- scripts/core/deviceipversion.yml
> add an extension to return the device IP version

- third_party/requirements.txt
Requirements failed to install due to stale lxml version; updating to 4.9.1.
> Update the lxml version requirement to 4.9.1

- scripts/core/PROG.rst
- scripts/core/cmdlist.yml
This change clarifies that commands appended to an immediate command list may execute synchronously, by blocking until the command is complete.
> clarify commands in an immediate command list may execute synchronously

- scripts/core/driver.yml
- scripts/parse_specs.py
This PR adds support for version-specific details, which could be useful for e.g. #12.
The syntax is similar to that for descriptions.  Example:
```yaml
details: 
- "1.0": "This detail is valid in version 1.0."
"1.5": "This detail is valid in version 1.5."
"1.6": "This detail would be valid in version 1.6."
- "1.0": "This is another detail that is valid in version 1.0."
"1.2": "This is another detail that is valid in version 1.2."
- "1.5": "This detail is only valid in version 1.5."
- "1.6": "This detail would only be valid in version 1.6."
```
> script update: support version-specific details

- scripts/core/EXT_Exp_SubAllocationProperties.rst
- scripts/core/common.yml
- scripts/core/subAllocationsProperties.yml
Depending on target platform, certain Level Zero drivers may split an L0 allocation into smaller sub-allocations for performance purposes. This extension allows applications to query for the number and size of those sub-allocations.
> Add sub-allocations properties extensions

- scripts/core/event.yml
- scripts/core/memory.yml
- scripts/core/module.yml
Fixes #42 
We should be able to allocate up to the maximum memory allocation size, not up to the maximum memory allocation size minus one.  Note, this is retroactive to all spec versions (so treated as a spec bugfix), and is not a v1.5-specific addition.
Also removes a few extraneous hyphens in `less-than` and `equal-to`.
> fix off-by-one error for maximum memory allocation size

- scripts/core/EXT_Exp_ImageViewPlanar.rst
- scripts/core/EXT_ImageView.rst
- scripts/core/EXT_ImageViewPlanar.rst
- scripts/core/common.yml
- scripts/core/imageview.yml
- scripts/core/imageviewplanar.yml
This is being used by several customers, and feedback is that it is good to be promoted to standard.
Extension will still be kept to facilitate transition.
> Move image view extension to standard

- scripts/core/PROG.rst
- scripts/generate_docs.py
- scripts/sysman/PROG.rst
Fixes several issues affecting older spec builds:
* The scripts do not handle "else" statements.  Fixed by inverting the "if" condition instead.
* The scripts were not properly handling "endif" statements.  Fixed by correcting the script regular expression.
> fix scripts to enable building older spec versions

- scripts/tools/common.yml
Signed-off-by: Jaime Arteaga<jaime.a.arteaga.molina@intel.com>
> Remove warning on missing definition of Tools env vars

- scripts/parse_specs.py
- scripts/templates/helper.py
> remove nullptr error code from params with mbz trait

- scripts/core/PROG.rst
- scripts/sysman/PROG.rst
- scripts/tools/PROG.rst
Correct initialize ze_device_properties_t to zero and set stype properly. This way samples show how to initialize these structs to avoid driver implementations to misread garbage values in pNext.
> Fix ze_device_properties_t in samples

- scripts/core/device.yml
Resolves #54
Signed-off-by: Will Damon \<will.damon@intel.com\>
> Clarify intended interpretation of 32-bit device id.

- scripts/core/PROG.rst
- Remove incorrect stipulation that `zeContextMakeMemoryResident` is Windows-only. It is a cross-platform API.
- Also, correct a spelling mistake.
Resolves #70
Signed-off-by: Will Damon \<will.damon@intel.com\>
> Clarify that zeContextMakeMemoryResident is a cross-platform API

- scripts/core/EXT_KernelMaxGroupSizeProperties.rst
- scripts/core/kernelMaxGroupSizeProperties.yml
Summary:
This extension provides the user with the ability to query the maximum group size that can be used to execute the kernel on the device. The implementation uses the resource requirements of the kernel (register usage, etc.) to determine what this group size should be.
Notes:
- This value may vary from one kernel to another as well as one device to another.
- This value will be less than or equal to `ze_device_compute_properties_t::maxTotalGroupSize`.
Resolves #28
Signed-off-by: Will Damon <wdamon@intel.com>
> Add an extension to get the kernel max group size properties.

- scripts/tools/GlobalTimestamps.yml
version tag ensures DDI tables maintain proper ordering
> Add version 1.5 to GlobalTimestamps ext

- scripts/core/driver.yml
This function retrieves a message associated with the returned code of the last call made.
Resolves: #61
> Add zeDriverGetLastResultString

- scripts/core/memory.yml
Resolves: #68
Define two new functions:
zeMemGetIpcHandleFromFileDescriptorExp
zeMemGetFileDescriptorFromIpcHandleExp
to allow users to construct an IPC memory handle from a file descriptor, or to get the file descriptor out of an IPC memory handle, respectively.
This allows applications to not need to know the details of how the driver creates the opaque IPC handle, and to intermix IPC opaque APIs (zeMemGetIpcHandle, zeMemOpenIpcHandle, etc) with explicit file descriptor APIs (e.g., ze_external_memory_export_fd_t).
> Add helper functions for IPC handle

- scripts/core/image.yml
Media formats are defined using the layout member, not the format type member
> Move restrictions about image buffers to under ze_image_type_t

- scripts/sysman/common.yml
- scripts/sysman/fabric.yml
- scripts/sysman/ras.yml
This reverts commits:
- 7de96547c9b3bc190606eb0a3327e465e6c52459
- 5ced682e98bf10002d2c3e519373a312f883dadd
...due to a binary incompatibility regression.
> Revert RAS Category and Fabric API commits (#35, #83)

- scripts/tools/GlobalTimestamps.yml
> Fix base type for zet_metric_global_timestamps_resolution_exp_t

- scripts/core/common.yml
- scripts/core/kernelMaxGroupSizeProperties.yml
- Added stype.
- Defined alias since original name didnt follow convention.
Resolves: #156
> Some fixes for kernel max group size extension

- scripts/core/PROG.rst
> Minor fix to kernel timestamp example in programming guide.

- .gitignore
- scripts/core/EXT_Exp_RTASBuilder.rst
- scripts/core/RTASBuilder.yml
- scripts/core/common.yml
- scripts/parse_specs.py
- scripts/templates/api.h.mako
- scripts/templates/helper.py
- third_party/requirements.txt
This extension provides the functionality to build ray tracing acceleration structures for 3D scenes on the host for use with GPU devices.
Resolves #146
> Add ray tracing acceleration structure build experimental extension

- scripts/tools/common.yml
- Add ZET_STRUCTURE_TYPE_METRIC_CALCULATE_EXP_DESC
- Add ZET_STRUCTURE_TYPE_METRIC_GLOBAL_TIMESTAMPS_RESOLUTION_EXP
- Deprecate ZET_STRUCTURE_TYPE_METRICS_CALCULATE_EXP_DESC
- Deprecate ZET_STRUCTURE_TYPE_GLOBAL_METRICS_TIMESTAMPS_EXP_PROPERTIES
Resolves #157 
Resolves #158
> Fix ZET typo to conform to naming convention.

- scripts/core/PROG.rst
- scripts/core/common.yml
- scripts/core/device.yml
- scripts/sysman/device.yml
> Add support for flexible device hierarchy model

- scripts/sysman/power.yml
CARD domain is technically for whole PCI card which might include more than just the GPU IP. So, adding separate GPU domain helps to provide GPU specific power related info.
Addresses: #223
> Add new GPU power domain

- scripts/core/EXT_Exp_MutableCommandList.rst
- scripts/core/common.yml
- scripts/core/mutableCommandList.yml
> Add experimental extension for mutable command lists

- scripts/core/residency.yml
Resolves: oneapi-src/level-zero-spec#240
> Add invalid argument error code to zeContextMakeMemoryResident

- scripts/sysman/EXT_Exp_VirtualFunctionManagement.rst
- scripts/sysman/common.yml
- scripts/sysman/virtualFunctionManagement.yml
Resolves: oneapi-src/level-zero-spec#248
> New Sysman API for VF telemetry

- scripts/core/EXT_Exp_CommandListClone.rst
- scripts/core/EXT_Exp_ImmediateCommandListAppend.rst
- scripts/core/EXT_Exp_MutableCommandList.rst
- scripts/core/immediateCommandListAppend.yml
- scripts/core/mutableCommandList.yml
- scripts/sysman/EXT_Exp_FirmwareSecurityVersion.rst
- scripts/sysman/common.yml
- scripts/sysman/firmwareSecurityVersion.yml
- scripts/tools/metricProgrammable.yml
- Add missing enumerations to programming guides
- Add numWaitEvents parameter to mutable command list update wait events API (needed for loader)
- Add range to phCommandLists description in append command lists extension
- Fix spelling error in sysman subdevice properties structure type name
- Fix immediate command list append API parameter description to work around script limitation
- Convert fixed-length character array parameters to constant pointers in programmable metrics and firmware secuirty version extensions
> Misc. patches to v1.9 release

- scripts/core/device.yml
https://spec.oneapi.io/level-zero/latest/core/api.html#structze__device__properties__t
```
uint32_t deviceId
[out] device id from PCI configuration Note, the device id uses little-endian format.
```
Missing a `.` before Note.
> Fix typo in for `device property`
