scripts/tools/PROG.rst
=> add a deprecation message for ZET_ENABLE_API_TRACING_EXP

scripts/sysman/common.yml, scripts/sysman/fabric.yml, scripts/sysman/ras.yml
Signed-off-by: Vaidyanathan Krishnamoorthy <vaidyanathan.krishnamoorthy@intel.com>
=> RAS Category and Fabric API added for spec v1.5

scripts/core/cmdlist.yml, scripts/core/cmdqueue.yml, scripts/core/context.yml, scripts/core/driver.yml, scripts/core/event.yml, scripts/core/fence.yml, scripts/core/image.yml, scripts/core/imageview.yml, scripts/core/memory.yml, scripts/core/module.yml, scripts/core/residency.yml, scripts/core/sampler.yml, scripts/core/virtual.yml, scripts/parse_specs.py, scripts/tools/tracing.yml
Add additional default errors
Add OUT_OF_HOST_MEMORY and OUT_OF_DEVICE_MEMORY errors as
default to all functions.
Resolves: #29
=> Add additional default errors

scripts/sysman/power.yml, scripts/sysman/powerLimits.yml
=> Mark zesPowerGetLimits and zesPowerSetLimits as deprecated

scripts/core/PROG.rst, scripts/core/memory.yml
=> Add host support for IPC allocations

scripts/sysman/memory.yml
=> Correct documentation for zesMemoryGetBandwidth

scripts/parse_specs.py
=> Fix handling of mbz attributes

scripts/sysman/memory.yml
Resolves #16 
Signed-off-by: Will Damon \<will.damon@intel.com\>
=> Explicitly state the timestamp unit for the memory bandwidth API

scripts/tools/EXT_Exp_GlobalTimestamps.rst, scripts/tools/GlobalTimestamps.yml, scripts/tools/common.yml
=> Add extension for global metrics timestamps

scripts/core/PROG.rst, scripts/core/event.yml, scripts/core/memory.yml
Also, fix some issues in related documentation.
Resolves: #89
=> Add zeMemPutIpcHandle and zeEventPoolPutIpcHandle

scripts/sysman/frequency.yml
=> Extend the SYSMAN Frequency Domain list to include a MEDIA Domain

scripts/core/cmdlist.yml
=> Add zeCommandListHostSynchronize

scripts/core/EXT_Exp_ImageView.rst, scripts/core/EXT_Exp_ImageViewPlanar.rst, scripts/core/SPIRV.rst
=> Fixup extension references and substitutions

scripts/parse_specs.py
=> add 1.6, 1.7 to all_versions

SECURITY.md
=> Import security documentation

scripts/tools/EXT_Exp_MetricExportData.rst, scripts/tools/EXT_Exp_MultiMetricValues.rst, scripts/tools/common.yml, scripts/tools/metricExportData.yml
=> Add support for machine independent calculation for metrics data

scripts/core/module.yml
=> Correct documentation on build logs lifetime

scripts/tools/EXT_Exp_MetricExportData.rst
From https://github.com/oneapi-src/level-zero-spec/pull/95
=> Fix html generation

scripts/core/EXT_Exp_BandwidthProperties.rst, scripts/core/EXT_LinkageInspection.rst, scripts/core/PROG.rst, scripts/core/common.yml, scripts/sysman/PROG.rst, scripts/sysman/common.yml, scripts/tools/PROG.rst, scripts/tools/common.yml
=> Fix pNext definition

scripts/sysman/common.yml, scripts/sysman/fabric.yml
Re-instated the Fabric error counters and API for 1.7
=> Added Fabric Error Counters and API

scripts/sysman/PROG.rst
=> Update ZES_ENGINE_GROUP_*_ALL description

scripts/tools/metric.yml
=> Promote ZET_METRIC_TYPE_IP_EXP out of experimental

scripts/sysman/common.yml, scripts/sysman/device.yml, scripts/sysman/engine.yml, scripts/sysman/fabric.yml, scripts/sysman/memory.yml, scripts/sysman/ras.yml
Sysman 7.0 spec release for engine, fabric, device, memory
=> Sysman 7.0 spec release for engine, fabric, device, memory

scripts/core/cmdlist.yml, scripts/core/cmdqueue.yml
=> Add clarification to immediate command lists execution

scripts/core/copy.yml
=> Add system memory hint for memory advise

scripts/sysman/device.yml
=> Add clarifications to board and serial number descriptions

scripts/core/eventQueryKernelTimestamps.yml
=> Fix timestamps results parameter attributes

scripts/sysman/PROG.rst, scripts/sysman/fabric.yml
and also add pseudo code for illustrative purposes
Addresses: #195
=> Clarify description for multi port throughput

scripts/core/driver.yml
=> Add API Version 1.7

scripts/sysman/power.yml
=> Add MEMORY power domain to enum

scripts/core/event.yml
=> Clarify usage of IPC event pools

scripts/sysman/temperature.yml
Added GPU board temperature metric to Temperature
=> Added GPU Board Temperature Metric

scripts/sysman/engine.yml, scripts/sysman/frequency.yml, scripts/sysman/power.yml, scripts/sysman/powerLimits.yml
API clean up for Sysman 2.0 update
=> Deprecated feature for 2.0 update

scripts/sysman/EXT_MemoryTimestampValidBits.rst, scripts/sysman/common.yml, scripts/sysman/memory.yml, scripts/sysman/memoryTimestampValidBits.yml
- Add proper stype for the extension structure
- document how struct is to be queried/returned
- move extension to separate yml file
Addresses: #229
=> Fixes to memory bandwidth extension

scripts/sysman/scheduler.yml
=> Deprecating compute unit debug mode

scripts/sysman/engine.yml
=> Fixup versioning on deprecated enumerations

scripts/sysman/firmware.yml
- it's not fit for purpose, so removing for now
- massage some other statements in firmware file
=> Remove firmware console logs API

scripts/core/PROG.rst
=> Fix device hierarchy envvar value in docs

scripts/run.py, scripts/templates/conf.py.mako
- Update Windows build environment to use Visual Studio 2022
- Update copyright year to 2024
=> Infrastructure adjustments

scripts/tools/EXT_Exp_MetricProgrammable.rst, scripts/tools/common.yml, scripts/tools/metricProgrammable.yml
=> Add support for programmable metrics

scripts/sysman/common.yml
This fixes and invalid reference during spec build
=> Fixup memory bandwidth properties structure name

scripts/core/EXT_Exp_ImmediateCommandListAppend.rst, scripts/core/immediateCommandListAppend.yml
=> Add experimental extension for immediate CL append CLs

scripts/core/EXT_Exp_CommandListClone.rst, scripts/core/cmdlist.yml, scripts/core/commandListClone.yml
=> Add experimental extension to clone a command list

scripts/tools/EXT_Exp_MetricProgrammable.rst, scripts/tools/metricProgrammable.yml
=> [tools] fixup programmable metrics exp ext typos

scripts/core/cmdlist.yml, scripts/core/cmdqueue.yml, scripts/core/event.yml
Resolves oneapi-src/level-zero-spec#267
=> Introspection APIs

scripts/core/EXT_EXP_BindlessImages.rst, scripts/core/bindlessimages.yml, scripts/core/common.yml
Resolves: oneapi-src/level-zero-spec#109
=> Add experimental extension for bindless images

scripts/sysman/engine.yml
Resolves: oneapi-src/level-zero-spec#250
=> Clarify engine stats details

scripts/sysman/frequency.yml
Resolves: oneapi-src/level-zero-spec#242
=> Add clarification for setting frequency defaults

scripts/sysman/firmware.yml
Resolves: oneapi-src/level-zero-spec#277
=> New firmware API for logging

scripts/tools/debug.yml
=> Add new ELF memory space for debugger

.github/workflows/scorecard.yml
Adding support for openssf workflow to the repository
=> Create scorecard.yml to establish openssf workflow

.github/workflows/scorecard.yml
Updated versions for checkout code, runanalysis, upload artifacts, code scanning, enabled publishing to dashboard.
=> updating versions for scorecard analysis

scripts/templates/helper.py
=> Fix order by version in DDI tables
